#!/bin/sh

set -e
cd "$(dirname "$0")/.."

name="janaz/webdav"
tz=$(tz=Australia/Melbourne date +%Y%m%d%H%M%S)
version=1

docker tag ${name} ${name}:${version}-${tz}
docker push ${name}:${version}-${tz}
docker push ${name}:latest
